
title: DIG2000
description: Syllabus for DIG2000 Introduction to Digital Media
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

plugins:
  - jekyll-remote-theme

remote_theme: mwmxyz/hacker
